### ISSUE TITLE
synabyte.pas's missing?

### ISSUE THREAD

**Issue by edwinyzh** [dimmaq/delphi-synapse#1]
I'm having an [email attachment sent via SMTP corruption issue](https://github.com/ezequieljuliano/Mailer4Delphi/issues/4) with the official Synapse codebase, thus wanted to try this to see if this version fix it, but got the following issue:
`[dcc32 Fatal Error] blcksock.pas(105): F1026 File not found: 'synabyte.dcu'`

Thanks.

**Comment by dimmaq** [comment]
I dont have synabyte.pas in origin synapse source. 
It is in modified fork https://github.com/TetrisSQC/SynapseTCP
